# write github actions to test terraform code
name: Terraform Test


defaults:
  run:
    working-directory: ./envs/dev
# This workflow will run on pushes to the main branch and on pull requests targeting the main branch.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        id: init
        run: terraform init -var="bucket_name=aws-david-20-dev-s3-bucket-state" -reconfigure
        continue-on-error: false

          # Run a terraform fmt for push
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Validate Terraform
        id: validate
        if: (success() || failure())
        run: terraform validate
        continue-on-error: false

      - name: Plan Terraform
        id: plan
        if: (success() || failure())
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: default
        run: terraform plan


